# Generated by Django 5.0 on 2023-12-06 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.FloatField()),
                ('image', models.ImageField(upload_to='clients/')),
                ('formatted_image', models.ImageField(null=True, upload_to='clients/')),
                ('inferred_model', models.FileField(null=True, upload_to='clients/')),
                ('overlayed_image', models.ImageField(null=True, upload_to='clients/')),
                ('model_image', models.ImageField(null=True, upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='goods/')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=10)),
                ('content', models.CharField(blank=True, max_length=400)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('image', models.ImageField(upload_to='reviews/')),
                ('formatted_image', models.ImageField(null=True, upload_to='reviews/')),
                ('inferred_model', models.FileField(null=True, upload_to='reviews/')),
                ('overlayed_image', models.ImageField(null=True, upload_to='reviews/')),
                ('model_image', models.ImageField(null=True, upload_to='reviews/')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.good')),
            ],
        ),
    ]
